Komugi/issue1
code-syncers/quiz-shower pull request #15
Opened 2023-09-30 16:32 UTC by komugi8

### Issue 番号

- Close #1

### 変更内容

- navigation barと画面遷移

### スクリーンショット

| Before | After |
| :----: | :---: |
|        |       |

### この PR はマージ可能な状態ですか

```
[x] Yes
[ ] No
```

### 確認事項

- [ ] アイコンをタップすると画面が遷移しているか

### その他

-

2023-10-01 14:13 UTC, keigomichi requested changes
レビューしました！

2023-10-01 14:13 UTC, keigomichi commented on lib/main.dart
> +class QuizShower extends StatelessWidget {
SHOULD: 慣習的に `HogeApp` というクラス名にしたいので、 `QuizShowerApp` とかにしましょうかね
```suggestion
class QuizShowerApp extends StatelessWidget {
```

2023-10-01 14:13 UTC, keigomichi commented on lib/main.dart
> +class QuizShower extends StatelessWidget {
SHOULD: `main.dart` のコード量が多くなるので、このクラスを `quiz_shower_app.dart` などに移してみてはいかがでしょうか？

2023-10-01 14:13 UTC, keigomichi commented on test/widget_test.dart
👍

2023-10-01 14:13 UTC, keigomichi commented on lib/ui/navigation/quiz_shower_navigation.dart
> +class QuizShowerNavigation extends StatefulWidget {
IMO: このクラスは `Scaffold` を返しているので、 `QuizShowerNavigation` という名前はあまり適切でないかも。実態に即して `HogeScaffold` とかが良いと個人的には思いました
なので、パスとしても `navigation/` に置くのはどうかなという感じ

2023-10-02 01:40 UTC, komugi8 commented on lib/main.dart
> +class QuizShower extends StatelessWidget {
りょーかいです！

2023-10-02 01:41 UTC, komugi8 commented on lib/main.dart
> +class QuizShower extends StatelessWidget {
そうします！

2023-10-02 01:41 UTC, komugi8 commented on lib/ui/navigation/quiz_shower_navigation.dart
> +class QuizShowerNavigation extends StatefulWidget {
確かにそうだね！
修正します！！

2023-10-02 02:51 UTC, keigomichi requested changes
コンフリクト解消お願いします 🙏

2023-10-02 11:23 UTC, komugi8 commented on lib/main.dart
> +class QuizShower extends StatelessWidget {
a6599a79e38aaec040da707856d144077c6f3ebf

2023-10-02 11:24 UTC, komugi8 commented on lib/main.dart
> +class QuizShower extends StatelessWidget {
69ca2c8ce41f38cc38b9caf5d3304a23b443250d

2023-10-02 11:26 UTC, komugi8 commented on lib/ui/navigation/quiz_shower_navigation.dart
> +class QuizShowerNavigation extends StatefulWidget {
bb2db3390e81921e0aa008636b3009a516e4f451

2023-10-02 11:40 UTC, keigomichi requested changes
1か所、提案があります 🙏 

あと、これは好みの問題だけど、 `lib/ui/screens` → `lib/ui/screen` で単数系で統一するのはいかがでしょう？

2023-10-02 11:40 UTC, keigomichi commented on lib/quiz_shower_app.dart
👍

2023-10-02 11:40 UTC, keigomichi commented on lib/navigation/quiz_shower_scaffold.dart
NITS: `lib/navigation` ではなく、 `lib/ui/widget` とかに配置すると良さそう？

2023-10-02 11:49 UTC, komugi8 commented on lib/navigation/quiz_shower_scaffold.dart
57222725dabf8a6de9d79ea8e110771a46c321b6
8cc417d9deeeb2dc0b1bd7be75aee0daa2d6ea8d

2023-10-02 12:01 UTC, keigomichi approved these changes
LGTM 🎉

2023-10-02 12:04 UTC, merged